la_poiz_wind:
    resource: "@LaPoizWindBundle/Resources/config/routing.yml"
    prefix:   /

LaPoizHighchartsBundle:
    resource: "@LaPoizHighchartsBundle/Resources/config/routing.yml"
    prefix:   /hgraph